// ===== MoleculeGenerator.ts =====
import { MoleculeTemplatesToGenerate } from "./MoleculeTemplatesToGenerate"
import type { MoleculeTemplateProps } from "./MoleculeBuilder"

// Validate no duplicate fileNames
function validateUniqueFileNames() {
  const fileNames = MoleculeTemplatesToGenerate.map((t) => t.fileName)
  const duplicates = fileNames.filter(
    (name, index) => fileNames.indexOf(name) !== index,
  )
  if (duplicates.length > 0) {
    throw new Error(
      `Duplicate fileName(s) found: ${[...new Set(duplicates)].join(", ")}`,
    )
  }
}

// Generate the TSX content for a molecule template
function generateMoleculeTSX(
  template: (typeof MoleculeTemplatesToGenerate)[number],
): string {
  const { fileName, wing, wingTop, wingBottom, wingLeft, wingRight, ...props } =
    template

  // Build the props string (excluding wing props)
  const propsArray = Object.entries(props)
    .filter(([_, value]) => value !== undefined)
    .map(([key, value]) => {
      if (typeof value === "string") {
        return `${key}="${value}"`
      }
      return `${key}={${value}}`
    })

  const propsString =
    propsArray.length > 0
      ? "\n            " + propsArray.join("\n            ")
      : ""

  // Handle wing props - allow override from parameters
  const wingDefault = wing !== undefined ? `"${wing}"` : "undefined"
  const wingTopDefault = wingTop !== undefined ? `"${wingTop}"` : "undefined"
  const wingBottomDefault =
    wingBottom !== undefined ? `"${wingBottom}"` : "undefined"
  const wingLeftDefault = wingLeft !== undefined ? `"${wingLeft}"` : "undefined"
  const wingRightDefault =
    wingRight !== undefined ? `"${wingRight}"` : "undefined"

  const wingProp = `\n            wing={wing ?? ${wingDefault}}`
  const wingTopProp =
    wingTop !== undefined
      ? `\n            wingTop={wingTop ?? ${wingTopDefault}}`
      : ""
  const wingBottomProp =
    wingBottom !== undefined
      ? `\n            wingBottom={wingBottom ?? ${wingBottomDefault}}`
      : ""
  const wingLeftProp =
    wingLeft !== undefined
      ? `\n            wingLeft={wingLeft ?? ${wingLeftDefault}}`
      : ""
  const wingRightProp =
    wingRight !== undefined
      ? `\n            wingRight={wingRight ?? ${wingRightDefault}}`
      : ""

  return `// Auto-generated by lib/src/MoleculeTemplateGenerator.ts
// DO NOT EDIT THIS FILE MANUALLY

import { Molecule } from 'lib/MoleculeTemplate';
import type { MoleculeTemplateProps } from 'lib/src/MoleculeBuilder';

export default function ${fileName}(props: MoleculeTemplateProps = {}) {
    const { wing, wingTop, wingBottom, wingLeft, wingRight, children } = props;

    return (
        <Molecule${propsString}${wingProp}${wingTopProp}${wingBottomProp}${wingLeftProp}${wingRightProp}
        >
            {children}
        </Molecule>
    );
}
`
}

// Generate the barrel file content
function generateBarrelFile(): string {
  const header = `// Auto-generated by lib/src/MoleculeTemplateGenerator.ts
// DO NOT EDIT THIS FILE MANUALLY

`
  const exports = MoleculeTemplatesToGenerate.map((template) => {
    return `export { default as ${template.fileName} } from "lib/generated/${template.fileName}"`
  })

  return header + exports.join("\n") + "\n"
}

// Create the generated folder and write files
async function generateFiles() {
  validateUniqueFileNames()

  const outputDir = "./lib/generated"

  // Empty out the output directory to remove any old files
  try {
    const existingFiles = await Array.fromAsync(
      new Bun.Glob("*.tsx").scan(outputDir),
    )
    for (const file of existingFiles) {
      const filePath = `${outputDir}/${file}`
      await Bun.file(filePath).unlink()
    }
    console.log(`Cleaned ${existingFiles.length} old file(s) from ${outputDir}`)
  } catch (error) {
    // Directory might not exist yet or be empty, which is fine
    console.log("Could not clean directory:", error)
  }

  // Generate a file for each template
  for (const template of MoleculeTemplatesToGenerate) {
    const content = generateMoleculeTSX(template)
    const filePath = `${outputDir}/${template.fileName}.tsx`

    await Bun.write(filePath, content)
    console.log(`Generated: ${filePath}`)
  }

  // Generate the barrel file
  const barrelContent = generateBarrelFile()
  const barrelPath = "./lib/molecule-templates.ts"
  await Bun.write(barrelPath, barrelContent)
  console.log(`Generated: ${barrelPath}`)

  console.log(
    `\nSuccessfully generated ${MoleculeTemplatesToGenerate.length} file(s) + barrel file`,
  )
}

// Run the generator
generateFiles()
