/**
 * Molecule Template Generator Tests
 *
 * Tests the generated molecule template files to ensure they match expected output.
 * Uses Bun's built-in snapshot testing to track changes over time.
 *
 * How to run:
 *   bun test                           - Run all tests
 *   bun test --watch                   - Run tests in watch mode
 *   bun test --update-snapshots        - Update snapshots after intentional changes
 *   bun test -u                        - Shorthand for updating snapshots
 *
 * What this tests:
 *   - Correct number of files are generated
 *   - All expected files exist in the generated directory
 *   - Each file's content matches the snapshot
 *   - Generated files have correct structure (imports, exports, comments)
 *   - Template props are correctly rendered in the output
 *
 * Snapshots are stored in: molecule-templates/src/__snapshots__/
 */

import { test, expect, describe } from "bun:test"
import { MoleculeTemplatesToGenerate } from "./MoleculeTemplatesToGenerate"
import path from "path"

const getOutputDir = () => {
  // Get the directory relative to the test file location
  return path.join(import.meta.dir, "../generated")
}

describe("MoleculeTemplateGenerator", () => {
  test("correct number of files are generated", async () => {
    const outputDir = getOutputDir()
    const files = await Array.fromAsync(new Bun.Glob("*.tsx").scan(outputDir))

    expect(files.length).toBe(MoleculeTemplatesToGenerate.length)
  })

  test("all expected files exist", async () => {
    const outputDir = getOutputDir()
    const files = await Array.fromAsync(new Bun.Glob("*.tsx").scan(outputDir))
    const fileNames = files.map((f) => f.replace(".tsx", "")).sort()
    const expectedNames = MoleculeTemplatesToGenerate.map(
      (t) => t.fileName,
    ).sort()

    expect(fileNames).toEqual(expectedNames)
  })

  test("generated files match snapshots", async () => {
    const outputDir = getOutputDir()
    const files = await Array.fromAsync(new Bun.Glob("*.tsx").scan(outputDir))

    for (const file of files.sort()) {
      const content = await Bun.file(`${outputDir}/${file}`).text()
      expect(content).toMatchSnapshot(file)
    }
  })

  test("each generated file has correct structure", async () => {
    const outputDir = getOutputDir()

    for (const template of MoleculeTemplatesToGenerate) {
      const filePath = `${outputDir}/${template.fileName}.tsx`
      const content = await Bun.file(filePath).text()

      // Check for auto-generated comment
      expect(content).toContain(
        "// Auto-generated by molecule-templates/src/MoleculeTemplateGenerator.ts",
      )
      expect(content).toContain("// DO NOT EDIT THIS FILE MANUALLY")

      // Check for required imports
      expect(content).toContain(
        'import {MachinePin} from "@adom-footprint-library/src/MachinePin"',
      )
      expect(content).toContain(
        'import {MachineContact} from "@adom-footprint-library/src/MachineContact"',
      )
      expect(content).toContain(
        "import { Molecule } from '@molecule-templates/MoleculeTemplate'",
      )

      // Check for function export with wing and children parameters
      expect(content).toContain(
        `export default function ${template.fileName}({ wing, children }`,
      )

      // Check for Molecule component
      expect(content).toContain("<Molecule")
    }
  })

  test("generated file contains correct props", async () => {
    const outputDir = getOutputDir()
    const template = MoleculeTemplatesToGenerate[0] // Test first template
    const filePath = `${outputDir}/${template.fileName}.tsx`
    const content = await Bun.file(filePath).text()

    // Check that template props are in the generated file
    expect(content).toContain(`type="${template.type}"`)
    expect(content).toContain(`size="${template.size}"`)
    expect(content).toContain(`pinType="${template.pinType}"`)
    // Check that wing is handled as a parameter with default
    expect(content).toContain(`wing={wing ?? "${template.wing}"`)
  })
})
