// ===== MachinePinContactGenerator.ts =====
import { MachinePinContactsToGenerate } from "./MachinePinContactToGenerate"

// Validate no duplicate fileNames
function validateUniqueFileNames() {
  const fileNames = MachinePinContactsToGenerate.map((t) => t.fileName)
  const duplicates = fileNames.filter(
    (name, index) => fileNames.indexOf(name) !== index,
  )
  if (duplicates.length > 0) {
    throw new Error(
      `Duplicate fileName(s) found: ${[...new Set(duplicates)].join(", ")}`,
    )
  }
}

// Derive properties from the type string
function derivePropertiesFromType(type: string) {
  const isPin = type.startsWith("MachinePin")

  return {
    baseComponent: isPin ? "MachinePin" : "MachineContact",
    propsType: isPin
      ? "SpecificMachinePinProps"
      : "SpecificMachineContactProps",
  }
}

// Generate the TSX content for a machine pin/contact component
function generateMachinePinContactTSX(
  template: (typeof MachinePinContactsToGenerate)[number],
): string {
  const { fileName, type } = template
  const { baseComponent, propsType } = derivePropertiesFromType(type)

  return `// Auto-generated by lib/src/MachinePinContactGenerator.ts
// DO NOT EDIT THIS FILE MANUALLY

import {${baseComponent}, ${propsType}} from "lib/src/${baseComponent}"


export const ${fileName} = (props:${propsType}) => {
  return (
    <${baseComponent} type="${type}" {...props}

    />

  );
}
`
}

// Generate the barrel file content
function generateBarrelFile(): string {
  const header = `// Auto-generated by lib/src/MachinePinContactGenerator.ts
// DO NOT EDIT THIS FILE MANUALLY

`
  const exports = MachinePinContactsToGenerate.map((template) => {
    return `export {${template.fileName} } from "lib/generated/${template.fileName}"`
  })

  return header + exports.join("\n") + "\n"
}

// Create the generated folder and write files
async function generateFiles() {
  validateUniqueFileNames()

  const outputDir = "./lib/generated"

  // Empty out the output directory to remove any old files
  try {
    const existingFiles = await Array.fromAsync(
      new Bun.Glob("*.tsx").scan(outputDir),
    )
    for (const file of existingFiles) {
      const filePath = `${outputDir}/${file}`
      await Bun.file(filePath).unlink()
    }
    console.log(`Cleaned ${existingFiles.length} old file(s) from ${outputDir}`)
  } catch (error) {
    // Directory might not exist yet or be empty, which is fine
    console.log("Could not clean directory:", error)
  }

  // Generate a file for each template
  for (const template of MachinePinContactsToGenerate) {
    const content = generateMachinePinContactTSX(template)
    const filePath = `${outputDir}/${template.fileName}.tsx`

    await Bun.write(filePath, content)
    console.log(`Generated: ${filePath}`)
  }

  // Generate the barrel file
  const barrelContent = generateBarrelFile()
  const barrelPath = "./lib/adom-footprint-library.ts"
  await Bun.write(barrelPath, barrelContent)
  console.log(`Generated: ${barrelPath}`)

  console.log(
    `\nSuccessfully generated ${MachinePinContactsToGenerate.length} file(s) + barrel file`,
  )
}

// Run the generator
generateFiles()
