import fs from "node:fs"
import path from "node:path"
import type { Command } from "commander"
import { getSessionToken, getSessionTokenFromNpmrc } from "lib/cli-config"
import { getRegistryApiKy } from "lib/registry-api/get-ky"
import kleur from "kleur"
import prompts from "prompts"

type SimpleRouteJson = Record<string, unknown> & {
  layerCount: number
  minTraceWidth: number
  connections: unknown[]
  obstacles: unknown[]
  bounds: {
    minX: number
    maxX: number
    minY: number
    maxY: number
  }
}

type ReportAutorouterOptions = {
  title?: string
  yes?: boolean
}

type CreateAutoroutingBugReportResponse = {
  autorouting_bug_report: {
    autorouting_bug_report_id: string
  }
}

export const AUTOROUTER_BUG_REPORT_VIEW_URL =
  "https://api.tscircuit.com/autorouting/bug_reports/view?autorouting_bug_report_id="

const isFiniteNumber = (value: unknown): value is number =>
  typeof value === "number" && Number.isFinite(value)

export const readSimpleRouteJson = (filePath: string): SimpleRouteJson => {
  const resolvedFilePath = path.resolve(filePath)
  let fileContents: string

  try {
    fileContents = fs.readFileSync(resolvedFilePath, "utf8")
  } catch {
    throw new Error(`Could not read Simple Route JSON file: ${filePath}`)
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(fileContents)
  } catch {
    throw new Error(`Could not parse Simple Route JSON file: ${filePath}`)
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(
      `${filePath} is not a Simple Route JSON input. Pass a phase-N.input.simple-route.json file generated by \`tsci build --autorouter-dump-srj\`.`,
    )
  }

  const record = parsed as Record<string, unknown>
  const bounds = record.bounds as Record<string, unknown> | undefined
  if (
    !Number.isInteger(record.layerCount) ||
    (record.layerCount as number) < 1 ||
    !isFiniteNumber(record.minTraceWidth) ||
    record.minTraceWidth <= 0 ||
    !Array.isArray(record.connections) ||
    !Array.isArray(record.obstacles) ||
    typeof bounds !== "object" ||
    bounds === null ||
    Array.isArray(bounds) ||
    !isFiniteNumber(bounds.minX) ||
    !isFiniteNumber(bounds.maxX) ||
    !isFiniteNumber(bounds.minY) ||
    !isFiniteNumber(bounds.maxY) ||
    bounds.minX >= bounds.maxX ||
    bounds.minY >= bounds.maxY
  ) {
    throw new Error(
      `${filePath} is not a Simple Route JSON input. Pass a phase-N.input.simple-route.json file generated by \`tsci build --autorouter-dump-srj\`.`,
    )
  }

  return parsed as SimpleRouteJson
}

const confirmPublicReport = async (yes?: boolean): Promise<boolean> => {
  if (yes) return true

  const publicNotice =
    "Autorouter bug reports are public and anyone can download the uploaded routing data."
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error(`${publicNotice} Re-run with --yes to confirm the upload.`)
  }

  const { confirmed } = await prompts({
    type: "confirm",
    name: "confirmed",
    message: `${publicNotice} Continue?`,
    initial: false,
  })
  return confirmed === true
}

export const createAutorouterBugReport = async ({
  title,
  simpleRouteJson,
}: {
  title: string
  simpleRouteJson: SimpleRouteJson
}): Promise<{ bugReportId: string; bugReportUrl: string }> => {
  if (!getSessionToken() && !getSessionTokenFromNpmrc()) {
    throw new Error("You must be logged in. Run `tsci login` and try again.")
  }

  const response = await getRegistryApiKy()
    .post("autorouting/bug_reports/create", {
      json: {
        title,
        simple_route_json: simpleRouteJson,
      },
    })
    .json<CreateAutoroutingBugReportResponse>()

  const bugReportId = response.autorouting_bug_report.autorouting_bug_report_id
  return {
    bugReportId,
    bugReportUrl: `${AUTOROUTER_BUG_REPORT_VIEW_URL}${bugReportId}`,
  }
}

const getReportErrorMessage = (error: unknown): string => {
  const status = (error as { status?: number })?.status
  if (status === 401) {
    return "Your tscircuit session is missing or expired. Run `tsci login` and try again."
  }
  if (status === 413) {
    return "This autorouting log is too large to report online. Attach the Simple Route JSON file to a GitHub issue instead."
  }

  const message = error instanceof Error ? error.message : String(error)
  return message.split("\n\nRequest Body:")[0]
}

export const registerReportAutorouter = (program: Command) => {
  program.commands
    .find((command) => command.name() === "report")!
    .command("autorouter")
    .description(
      "Create a public autorouter bug report from a Simple Route JSON input",
    )
    .argument(
      "<file>",
      "Path to phase-N.input.simple-route.json from --autorouter-dump-srj",
    )
    .option("--title <title>", "Short description of the routing problem")
    .option("-y, --yes", "Confirm upload of a public bug report")
    .action(async (file: string, options: ReportAutorouterOptions) => {
      try {
        const simpleRouteJson = readSimpleRouteJson(file)
        if (!(await confirmPublicReport(options.yes))) {
          console.log("Report cancelled.")
          return
        }
        const title =
          options.title?.trim() || path.basename(file, path.extname(file))
        const { bugReportUrl } = await createAutorouterBugReport({
          title,
          simpleRouteJson,
        })

        console.log(kleur.green("Autorouter bug report created:"))
        console.log(bugReportUrl)
      } catch (error) {
        console.error(kleur.red(getReportErrorMessage(error)))
        process.exitCode = 1
      }
    })
}
