import fs from "node:fs"
import path from "node:path"
import { glob } from "glob"
import type { AnyCircuitElement } from "circuit-json"
import { parseKicadModToCircuitJson } from "kicad-component-converter"
import { extractGitHubInfo } from "../shared/extract-github-info"

export interface CachedKicadRepoInfo {
  packageDirName: string
  packagePath: string
  kicadModFiles: string[]
  exportsMap: Record<string, string>
}

const FOOTPRINT_ELEMENT_TYPES = new Set<AnyCircuitElement["type"]>([
  "pcb_smtpad",
  "pcb_plated_hole",
  "pcb_silkscreen_text",
  "pcb_silkscreen_line",
  "pcb_silkscreen_rect",
  "pcb_silkscreen_circle",
  "pcb_silkscreen_path",
])

const toPosixPath = (value: string) => value.split(path.sep).join("/")

const resolveWithinPackage = (packagePath: string, relativePosix: string) =>
  path.join(packagePath, ...relativePosix.split("/"))

const filterFootprintElements = (
  elements: AnyCircuitElement[],
): AnyCircuitElement[] =>
  elements.filter((element) => FOOTPRINT_ELEMENT_TYPES.has(element.type))

export async function cacheKicadFootprints(
  packageName: string,
  cwd: string = process.cwd(),
): Promise<CachedKicadRepoInfo | null> {
  const nodeModulesPath = path.join(cwd, "node_modules")

  const info = extractGitHubInfo(packageName)
  const packageDirName = info ? info.repo : packageName
  const packagePath = path.join(nodeModulesPath, packageDirName)

  if (!fs.existsSync(packagePath)) {
    return null
  }

  const matchedFiles = await glob("**/*.kicad_mod", {
    cwd: packagePath,
    absolute: false,
  })

  if (matchedFiles.length === 0) {
    return null
  }

  const kicadModFiles = matchedFiles.map(toPosixPath).sort()
  const cacheRoot = path.join(packagePath, ".tsci-cache")

  if (fs.existsSync(cacheRoot)) {
    fs.rmSync(cacheRoot, { recursive: true, force: true })
  }

  const exportsMap: Record<string, string> = {}

  console.log(
    `\nConverting ${kicadModFiles.length} KiCad footprint(s) to cached modules...`,
  )

  for (const relativePosix of kicadModFiles) {
    const sourcePath = resolveWithinPackage(packagePath, relativePosix)
    const cacheRelativePosix = path.posix.join(
      ".tsci-cache",
      relativePosix.replace(/\.kicad_mod$/, ".mjs"),
    )
    const cacheFilePath = resolveWithinPackage(packagePath, cacheRelativePosix)

    fs.mkdirSync(path.dirname(cacheFilePath), { recursive: true })

    let footprintElements: AnyCircuitElement[]
    try {
      const raw = fs.readFileSync(sourcePath, "utf8")
      const circuitJson = await parseKicadModToCircuitJson(raw)
      footprintElements = filterFootprintElements(circuitJson)
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error)
      throw new Error(
        `Failed to convert ${relativePosix} to Circuit JSON: ${reason}`,
      )
    }

    const moduleSource =
      "// Auto-generated by tsci install\n" +
      `const footprint = ${JSON.stringify(footprintElements, null, 2)};\n\n` +
      "export default footprint;\n"

    fs.writeFileSync(cacheFilePath, moduleSource)

    exportsMap[`./${relativePosix}`] = `./${cacheRelativePosix}`
  }

  console.log(
    `Cached footprint modules written to ${path.relative(cwd, cacheRoot)}`,
  )

  return {
    packageDirName,
    packagePath,
    kicadModFiles,
    exportsMap,
  }
}
