import { mkdir, readdir, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import {
  analyzeSchematicPlacement,
  createSchematicPlacementIssueArtifacts,
} from "@tscircuit/circuit-json-schematic-placement-analysis"
import type { PlatformConfig } from "@tscircuit/props"
import type { AnyCircuitElement, CircuitJson } from "circuit-json"
import type { Command } from "commander"
import { getCircuitJsonForCheck, resolveCheckInputFilePath } from "../shared"

export const checkSchematicPlacement = async (file?: string) => {
  const resolvedInputFilePath = await resolveCheckInputFilePath(file)
  const circuitJson = (await getCircuitJsonForCheck({
    filePath: resolvedInputFilePath,
    platformConfig: {
      pcbDisabled: true,
      routingDisabled: true,
      placementDrcChecksDisabled: true,
    } satisfies PlatformConfig,
    allowPrebuiltCircuitJson: true,
  })) as AnyCircuitElement[]

  const analysis = analyzeSchematicPlacement(circuitJson as CircuitJson)
  return {
    output: analysis.getString(),
    artifacts: createSchematicPlacementIssueArtifacts(
      circuitJson as CircuitJson,
      { analysis },
    ),
  }
}

export const registerCheckSchematicPlacement = (program: Command) => {
  program.commands
    .find((c) => c.name() === "check")!
    .command("schematic-placement")
    .description("Analyze schematic component placement")
    .argument("[file]", "Path to the entry file")
    .action(async (file?: string) => {
      try {
        const { output, artifacts } = await checkSchematicPlacement(file)
        console.log(output)
        const outputDir = path.resolve("dist", "schematic-placement")
        // Remove only files generated by this command, so resolved issues from
        // previous runs do not remain alongside the current reports.
        const previousFiles = await readdir(outputDir, {
          withFileTypes: true,
        }).catch((error: NodeJS.ErrnoException) => {
          if (error.code === "ENOENT") return []
          throw error
        })
        for (const entry of previousFiles) {
          if (entry.isFile() && /^issue-\d+-[A-Za-z]+\.svg$/.test(entry.name)) {
            await rm(path.join(outputDir, entry.name))
          }
        }
        if (artifacts.length > 0) await mkdir(outputDir, { recursive: true })
        for (const artifact of artifacts) {
          const outputPath = path.join(outputDir, artifact.fileName)
          await writeFile(outputPath, artifact.content)
          console.log(`Schematic placement artifact written to ${outputPath}`)
        }
      } catch (error) {
        console.error(error instanceof Error ? error.message : String(error))
        process.exit(1)
      }
    })
}
