// ===== MarginPackerTestGenerator.ts =====
import { MarginPackerTestsToGenerate } from "./MarginPackerTestsToGenerate"
import { calculateMolecule } from "../MoleculeCalculator"
import {
  calculateContactPositions,
  calculateContactPositionsForMargins,
} from "../MoleculeMarginPacker"
import * as fs from "fs"
import * as path from "path"

// Generate the TSX content for a margin packer test
function generatePackingTestTSX(
  config: (typeof MarginPackerTestsToGenerate)[number],
): string {
  const { moleculeTemplate, contactType, testFileName } = config
  const { fileName, ...moleculeProps } = moleculeTemplate

  // Calculate the molecule to get margins
  const moleculeResult = calculateMolecule({
    type: moleculeProps.type,
    size: moleculeProps.size,
    pinType: moleculeProps.pinType,
    wing: moleculeProps.wing,
    roundEdges: moleculeProps.roundEdges,
  })

  // Use the specified contact type from config (allows Medium contacts on Large pin molecules)
  const contactBoundingBoxSize = contactType === "Medium" ? 2 : 6

  // Calculate contact positions (either all margins or specific margins)
  const contactPositions = config.marginsToFill
    ? calculateContactPositionsForMargins(
        moleculeResult.margins,
        contactBoundingBoxSize,
        config.marginsToFill,
        config.alignment || "center",
      )
    : calculateContactPositions(
        moleculeResult.margins,
        contactBoundingBoxSize,
        config.alignment || "center",
      )

  // Determine contact component type based on config contact type
  const contactComponentName =
    contactType === "Medium" ? "MachineContactMedium" : "MachineContactLarge"

  // Build the props string for the Molecule component
  const propsArray = Object.entries(moleculeProps)
    .filter(([_, value]) => value !== undefined)
    .map(([key, value]) => {
      if (typeof value === "string") {
        return `${key}="${value}"`
      }
      return `${key}={${value}}`
    })

  const propsString =
    propsArray.length > 0
      ? "\n            " + propsArray.join("\n            ")
      : ""

  // Generate the contact components JSX
  const contactsJSX = contactPositions
    .map((pos) => {
      return `            <${contactComponentName} name="${pos.name}" pcbX={${pos.pcbX}} pcbY={${pos.pcbY}} />`
    })
    .join("\n")

  // Generate summary comment
  const filledMargins = config.marginsToFill
    ? config.marginsToFill.join(", ")
    : moleculeResult.margins.map((m) => m.name).join(", ")
  const summary = `// Total contact positions: ${contactPositions.length}
// Contact type: ${contactComponentName}
// Margins filled: ${filledMargins}`

  return `// Auto-generated by lib/src/MarginPackerTests/MarginPackerTestGenerator.ts
// DO NOT EDIT THIS FILE MANUALLY

${summary}

import { ${contactComponentName} } from '@tsci/imrishabh18.library';
import { Molecule } from 'lib/MoleculeTemplate';

export default function ${testFileName}PackingTest() {
    return (
        <Molecule${propsString}
        >
${contactsJSX}
        </Molecule>
    );
}
`
}

// Create the generated folder and write files
async function generateFiles() {
  const outputDir = path.join(__dirname, "generated")

  // Get list of existing files
  const existingFiles = fs
    .readdirSync(outputDir)
    .filter((f) => f.endsWith(".tsx"))

  // Build list of files we want to generate
  const newFileNames = MarginPackerTestsToGenerate.map(
    (config) => `${config.testFileName}PackingTest.tsx`,
  )

  // Delete files that are no longer defined
  for (const existingFile of existingFiles) {
    if (!newFileNames.includes(existingFile)) {
      const filePath = path.join(outputDir, existingFile)
      fs.unlinkSync(filePath)
      console.log(`Deleted: ${filePath}`)
    }
  }

  console.log(
    `Generating ${MarginPackerTestsToGenerate.length} packing test files...\n`,
  )

  for (const config of MarginPackerTestsToGenerate) {
    const content = generatePackingTestTSX(config)
    const filePath = `${outputDir}/${config.testFileName}PackingTest.tsx`

    await Bun.write(filePath, content)
    console.log(`Generated: ${filePath}`)
  }

  console.log(
    `\nSuccessfully generated ${MarginPackerTestsToGenerate.length} packing test files`,
  )
}

// Run the generator
generateFiles()
